version: '3'
services:
  generate-assets:
    build: 
      context: .
      dockerfile: Dockerfile
    image: guardianconnector-change-detection:latest
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - INPUT_FILE=example.geojson
      - ENVIRONMENT=docker
    command: python docker-generate.py --input ${INPUT_FILE}

  tileserver-gl:
    build:
      context: .
      dockerfile: Dockerfile.tileserver
    ports:
      - "8080:8080"
    volumes:
      - ./outputs/example/mapbox-map:/data
    depends_on:
      - generate-assets

  compile-composite-raster:
    image: guardianconnector-change-detection:latest
    volumes:
      - .:/app
    depends_on:
      - tileserver-gl
    environment:
      - INPUT_FILE=example.geojson
      - ENVIRONMENT=docker
    command: python docker-tileserver-compile.py --input ${INPUT_FILE}