version: '3'
services:
  generate-assets:
    build: 
      context: .
      dockerfile: Dockerfile
    image: guardianconnector-change-detection:latest
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - INPUT_GEOJSON_FILE=${INPUT_GEOJSON_FILE}
      - INPUT_T0_FILE=${INPUT_T0_FILE}
      - INPUT_T1_FILE=${INPUT_T1_FILE}
      - OUTPUT=${OUTPUT}
      - ENVIRONMENT=docker
    command: ${COMMAND}

  tileserver-gl:
    build:
      context: .
      dockerfile: Dockerfile.tileserver
    ports:
      - "8080:8080"
    volumes:
      - ./outputs/${OUTPUT}/mapgl-map:/data
    depends_on:
      - generate-assets

  compile-composite-raster:
    image: guardianconnector-change-detection:latest
    volumes:
      - .:/app
    depends_on:
      - tileserver-gl
    env_file:
      - .env
    environment:
      - INPUT_GEOJSON_FILE=${INPUT_GEOJSON_FILE}
      - OUTPUT=${OUTPUT}
      - ENVIRONMENT=docker
    command: python docker-tileserver-compile.py --geojson ${INPUT_GEOJSON_FILE} --output ${OUTPUT}
